# Generated by Django 6.0.3 on 2026-03-29 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        help_text="Введите категорию продукта",
                        max_length=150,
                        verbose_name="Название категории",
                    ),
                ),
                (
                    "category_description",
                    models.TextField(
                        blank=True,
                        help_text="Опишите категорию",
                        null=True,
                        verbose_name="Описание категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        help_text="Введите наименование продукта",
                        max_length=150,
                        verbose_name="Наименование продукта",
                    ),
                ),
                (
                    "product_description",
                    models.TextField(
                        blank=True,
                        help_text="Опишите продукт",
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "product_photo",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фото",
                        null=True,
                        upload_to="products/photo",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "product_price",
                    models.IntegerField(
                        help_text="ВВедите цену продукта",
                        verbose_name="Цена за покупку",
                    ),
                ),
                ("created_at", models.DateTimeField(verbose_name="Дата создания")),
                (
                    "updated_at",
                    models.DateTimeField(verbose_name="Дата последнего изменения"),
                ),
                (
                    "product_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Введите категорию продукта",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="Категория продукта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["product_category", "product_price"],
            },
        ),
    ]
